# AetherWG default tunnel (edit Endpoint to your VPS)
[Interface]
PrivateKey = MC6nTEO/IWG7pwbyxtlAFNs1o1EGoR+4LabauoLacH0=
Address = 10.66.66.2/32
DNS = 1.1.1.1, 1.0.0.1
MTU = 1280

[Peer]
PublicKey = mEQl6fyzNeeWgD0IQTV/Lvx6nEnDifWX1Dygt4lxjw4=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
Endpoint = 127.0.0.1:51820
